### ISSUE TITLE
Better and consistent versioning

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/event-formation-unit#130]
`CMakeLists.txt` has:
```
set(event-formation-unit_VERSION_MAJOR 1)
set(event-formation-unit_VERSION_MINOR 0)
```

But `version_num.h` has:
```
#define EFU_VER_MAJ 0
#define EFU_VER_MIN 1
#define EFU_VER_BUILD 1
```

So which is it?

It should probably be defined in one place, probably in CMake and then propagated into precompiler variables. But also, I think like there might be some use to having it in some sort of a struct or class that can answer backwards-compatibilty questions based on the logic of semantic versioning.

**Comment by martukas** [comment]
@mortenjc comments on this?

**Comment by mortenjc** [comment]
This could well be in CMAKE somehow as long as it ripples down into the C++ code so we can use 
it from there. 
This does not solve the more fundamental problems of handling version numbers, so
I would await some discussion on this.

I have previously followed a convention used by the Intel DPDK developer 
community, where the version numbers were kept in a separate file, and bumped using 
scripts that used sed to increment them.

**Comment by SkyToGround** [comment]
I think it is better to (as we mentioned during the meeting) set the version number using a Git tag. It is fully possible to have CMake pull a version string (that is compiled into the application) from a Git tag and doing it like this will also make it clear if you have the actual version in question or if you have compiled the application from some random commit.

**Comment by mortenjc** [comment]
So what happens to version number if there is no tag - reported version
is 0.0.0 ?

**Comment by SkyToGround** [comment]
Thats for us to decide but I am thinking that a good alternative is to set the version number to that of the last version tag with some extra characters that indicated that it is a development of that version.

**Comment by martukas** [comment]
@SkyToGround I am not quite sure where you are going with this. We have two different things in play here:
* semantic version, which is more or less manually set (since our human brains are the only things around with any semantic insight), and
* git commit hash (I guess that's what you man by git tag?) which is automatic, more granular and gives you the guarantee you desire

I believe the latter is already taken care of via the build string, which includes the git hash. The semantic version then is a separate issue, but it should still be set in one place only. My bet is on CMake because you can pass that information down into defines, but it's not as easy the other way around. @mortenjc you can make your sed scripts modify the CMake file just as well, can't you?

**Comment by mortenjc** [comment]
done, semantic versioning implemented and release scripts have been created
