### ISSUE TITLE
remove /utils/srsdaq and others obsolete scripts?

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/event-formation-unit#144]
Some of this stuff probably belongs in essdaq and is obsolete. Doro brought this up in chat.
@mortenjc  what do you think?

**Comment by mortenjc** [comment]
agree, we should go through the subdirectories and weed this out, also there are some luascript parsers for wireshark which may be better placed in essdaq, ansd other stuff too.

**Comment by mortenjc** [comment]
merged
