### ISSUE TITLE
Build generators on Jenkins

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/event-formation-unit#154]
It seems that TCLAP is not available on the docker images, so the generator programs for the EFU are not built. So, you could find out that you broke the code only when you eventually build on a local machine that has this available. Is this as intended, or an omission? @amues @mortenjc ?

**Comment by martukas** [comment]
Just confirm that all generators are actually built on jenkins

**Comment by mortenjc** [comment]
ok, firstly I am removing all references to TCLAP which is not what we use in ECDC, secondly I am making PCAP REQUIRED for the build. Then I will probably have broken something which I will then fix.

**Comment by mortenjc** [comment]
There is a conan package for libpcap which I am testing
cmake_installer/3.10.0@conan/stable

**Comment by mortenjc** [comment]
merged
