### ISSUE TITLE
Include common files and libs for benchmark tests

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/event-formation-unit#171]
There is now a need to manually add a lot of common source files (such as clustering code) and explicitly link to libraries that EFU uses (like logger, h5) when creating benchmark targets. Maybe all these should be linked to by default using the create_benchmark_executable() CMake function? As we start creating more benchmark tests, this problem may become more common.

**Comment by mortenjc** [comment]
close for now. We do not yet do any benchmark code
