### ISSUE TITLE
Improvements to PCAP reader

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/event-formation-unit#177]
PCAP reader should provide some information on expected size of data in file. Perhaps scan the file and find out how many UDP packets there are?

**Comment by martukas** [comment]
The main idea is to somehow estimate how much data to expect out of the file

**Comment by martukas** [comment]
The main idea is to somehow estimate how much data to expect out of the file

**Comment by martukas** [comment]
The main idea is to somehow estimate how much data to expect out of the file

**Comment by mortenjc** [comment]
Will add option -r for read-only
this will count the number of packets and print the stats but not transmit UDP
