### ISSUE TITLE
Do not use C's exit command

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/event-formation-unit#178]
Using `exit(1)` or the like while in a loop is bad practice. It does not clean up objects, ensure RAII and may end up not closing files out properly, etc..

1) If in main, just use `return(EXIT_FAILURE)` or `return(EXIT_SUCCESS)`
2) If in function, throw an exception and have main catch it and terminate appropriately.

I am now doing this properly in whatever code I am touching on, but you should go back and fix this in all other executables, modules, generators and utilities...

**Comment by mortenjc** [comment]
Sounds good in theory - however the use of threads may not make this straight forward. 
We should discuss the precise requirements. What if
3. function is in a thread ?

**Comment by martukas** [comment]
Yes, but I was seeing this in small programs like streamers and generators.
