### ISSUE TITLE
Should grafana stats use unsigned types?

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/event-formation-unit#183]
NewStats, which defines grafana stats takes an `int64` reference. I don't see us using negative stat values anywhere. Is this some requirement of graphite, or else should we not use a type with more resolution like `size_t` or `uint64_t`?

**Comment by SkyToGround** [comment]
The stats should definitely be of a signed type in my opinion. There are several reasons, one of them being that I make use of the type being singed in my code. The main problem with unsigned types is that they do not behave like numbers, i.e. 4-5 ≠-1.

**Comment by mortenjc** [comment]
ok, just talked to Jonas about this. We agreed that for now we do nothing as we can see some cases 
where negative values could be useful, and that it actually works now. If we later decide that this is ugly, then we can always do something about it.
