### ISSUE TITLE
Reduce docker image size

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/event-formation-unit#211]
Jack has slimmed the docker images for the File Writer and Forwarder to drastically reduce the disk space required when running the system tests. The same should be done for the EFU.

**Comment by mortenjc** [comment]
Sounds good, any hints to how this is done?

**Comment by rerpha** [comment]
I can do it, at the moment the EFU docker image has several layers and stores the conan cache, those are two easy ways it can be reduced. I'll give this a go soon, as i've just done the same for the forwarder and file-writer.  :+1:

**Comment by matthew-d-jones** [comment]
To explain further:
When the container image for the EFU is built, at every step in the dockerfile the result is cached as a "layer". This results in big disk use, because for example, the base image of the container has to exist in every one of the cached layers.
We want to have some cached layers so that if you change some code it doesn't have to repeat the earlier build steps such as installing system dependencies and conan packages, but currently the image has far more layers than necessary.

**Comment by mortenjc** [comment]
What's the status on this one? Jack is this still your plan to look at this?

**Comment by mortenjc** [comment]
Closing, will reopen if this causes problems in the future
