### ISSUE TITLE
Better unit tests for adc pipeline producers

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/event-formation-unit#216]
Need explicit tests to confirm that flat buffers include a proper header with fb id.
While for now it seems the headers are correct, as confirmed by file writer picking up on them, it would be safer to have this confirmed higher up in the data cascade.
We may at some point end up refactoring the producer classes, at which point it will be crucial to confirm that everything works the same.

**Comment by SkyToGround** [comment]
This is already tested in unit tests.
