### ISSUE TITLE
Implement improved GdGEM utpc algorithm

### ISSUE THREAD

**Issue by dorotheapfeiffer** [ess-dmsc/event-formation-unit#269]

**Comment by dorotheapfeiffer** [comment]
The idea of this issue is to hunt down the origin(s) of data losses and scrambled time stamps. I think there are actually four points where data is lost at high rates, on the hybrids, in the FEC, the network card and in the EFU (we have seen it before in all locations besides the network card, since we never studied that). The data loss on the hybrid is difficult to monitor, but to monitor problems on the FEC, the wireshark plugin has been updated to look for time stamp errors. In the EFU are already stats for fifo errors etc,and we check for FEC frame counter errors. I think we should add error counters for timestamp sequence errors and timestamp overflows.

**Comment by mortenjc** [comment]
This comment was for issue_270 ?

**Comment by mortenjc** [comment]
merged
