### ISSUE TITLE
Extend stats in EFU to hunt down SRS data loss/time scrambling 

### ISSUE THREAD

**Issue by dorotheapfeiffer** [ess-dmsc/event-formation-unit#270]

**Comment by mortenjc** [comment]
Seing no lost data in Wireshark doesn't mean that packets
are not lost before they reach the efu. Wireshark has high
priority and large buffers. But the OS buffers may be smaller.
Whole packets can be lost due to full buffers before reaching
the EFU.
 
You would see this as fc_seq_errors I guess. If no such errors
then packets have arrived at the EFU. It would be good to
compare the packet counters to see that all packets
sent from the srs also are received by the input thread.

**Comment by mortenjc** [comment]
I couldn't find color coding for lua script but you can use a construction like this

if error_condition ~= 1 then
   pinfo.cols.info = string.format("FEC: %d, Hits: %3d, Markers: %3d, Time error: %3d", fecid, hit_id, marker_id, time_error)
else
   pinfo.cols.info = "XXXXXXXX"
end

And the entire "Info" field will change depending on the condition. So if you have a relevant 
counter (time_error?) this might help?

**Comment by dorotheapfeiffer** [comment]
Thanks a lot for checking, so the possibility to colour realy does not seem to exist. 

I think we got now everything covered with the error counters in GdGEM:

Errors of the data inside the jumbo frames:

- frame_seq_error: frame counter has gaps or is in the wrong order

- framecounter_overflow: just for info, should not overflow in a long time

- timestamp_seq_order: fec timestamp arrives in wrong order (if the frame counter is correct, the FEC screws up the data before it sends it)

- timestap_lost_error: In the header of each jumbo frame is the overflow field, that tells us whether in the previous frame there was a marker/timestamp for one of the 16 VMMs per FEC.  If we miss a marker/timestamp for a vmm, we must have either lost a frame, or the FEC firmware has a problem in composing the header

- timestamp_overflow: just for info, should not overflow more than once every two days

FIFO errors:
-  fifo_seq_errors: data length 0 ad index in FIFO, position is not filled?

- fifo_push_errors: Data cannot be put into FIFO, does that mean the FIFO has not been emptied at this position?

Regarding the FIFO errors, at high rate I would expect fifo_push_errors, but when does one see fifo_seq_errors?

Are there ways to monitor dropped frames directly at the network card. iPerf ?

Cheers

Doro

**Comment by dorotheapfeiffer** [comment]
Can be closed, the changes were implemented with issue #269 and #271
