### ISSUE TITLE
gperf doesn't work

### ISSUE THREAD

**Issue by MortenHilkerSkaaning** [ess-dmsc/event-formation-unit#294]
Building with gperf fails on mac.

Cmake output:

CMake Error at Utilities.cmake:69 (target_link_libraries):
  The keyword signature for target_link_libraries has already been used with
  the target "udpgen_hits".  All uses of target_link_libraries with a target
  must be either all-keyword or all-plain.

  The uses of the keyword signature are here:

   * Utilities.cmake:63 (target_link_libraries)

Call Stack (most recent call first):
  src/generators/CMakeLists.txt:14 (create_executable)

-- *** Skipping benchmark for NMXClustererBenchmarkTest (can be enabled by cmake -DGOOGLE_BENCHMARK=YES)
CMake Error at Utilities.cmake:69 (target_link_libraries):
  The keyword signature for target_link_libraries has already been used with
  the target "nmxgen_readouts".  All uses of target_link_libraries with a
  target must be either all-keyword or all-plain.

  The uses of the keyword signature are here:

   * Utilities.cmake:63 (target_link_libraries)

Call Stack (most recent call first):
  src/gdgem/generators/CMakeLists.txt:12 (create_executable)

-- *** Skipping benchmark for MBDataParserBenchmarkTest (can be enabled by cmake -DGOOGLE_BENCHMARK=YES)
-- *** Skipping benchmark for MBEventBuilderBenchmarkTest (can be enabled by cmake -DGOOGLE_BENCHMARK=YES)
CMake Error at Utilities.cmake:69 (target_link_libraries):
  The keyword signature for target_link_libraries has already been used with
  the target "mbgen_hits".  All uses of target_link_libraries with a target
  must be either all-keyword or all-plain.

  The uses of the keyword signature are here:

   * Utilities.cmake:63 (target_link_libraries)

Call Stack (most recent call first):
  src/multiblade/generators/CMakeLists.txt:14 (create_executable)

CMake Error at Utilities.cmake:69 (target_link_libraries):
  The keyword signature for target_link_libraries has already been used with
  the target "mggen_readouts".  All uses of target_link_libraries with a
  target must be either all-keyword or all-plain.

  The uses of the keyword signature are here:

   * Utilities.cmake:63 (target_link_libraries)

Call Stack (most recent call first):
  src/multigrid/generators/CMakeLists.txt:15 (create_executable)

CMake Error at Utilities.cmake:69 (target_link_libraries):
  The keyword signature for target_link_libraries has already been used with
  the target "udpgen_jalousie".  All uses of target_link_libraries with a
  target must be either all-keyword or all-plain.

  The uses of the keyword signature are here:

   * Utilities.cmake:63 (target_link_libraries)

Call Stack (most recent call first):
  src/jalousie/CMakeLists.txt:82 (create_executable)

CMake Error at Utilities.cmake:69 (target_link_libraries):
  The keyword signature for target_link_libraries has already been used with
  the target "udpgen_jalousie2".  All uses of target_link_libraries with a
  target must be either all-keyword or all-plain.

  The uses of the keyword signature are here:

   * Utilities.cmake:63 (target_link_libraries)

Call Stack (most recent call first):
  src/jalousie/generators/CMakeLists.txt:13 (create_executable)

-- Found ASIO: /Users/mortenhilkerskaaning/.conan/data/asio/1.13.0/bincrafters/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
-- Test ADC packets in path: /Users/mortenhilkerskaaning/dev/event-formation-unit/src/adc_readout/test//
CMake Error at Utilities.cmake:69 (target_link_libraries):
  The keyword signature for target_link_libraries has already been used with
  the target "udpgen_pcap".  All uses of target_link_libraries with a target
  must be either all-keyword or all-plain.

  The uses of the keyword signature are here:

   * Utilities.cmake:63 (target_link_libraries)

Call Stack (most recent call first):
  src/tools/CMakeLists.txt:15 (create_executable)

CMake Error at Utilities.cmake:69 (target_link_libraries):
  The keyword signature for target_link_libraries has already been used with
  the target "efu".  All uses of target_link_libraries with a target must be
  either all-keyword or all-plain.

  The uses of the keyword signature are here:

   * Utilities.cmake:63 (target_link_libraries)

Call Stack (most recent call first):
  src/efu/CMakeLists.txt:24 (create_executable)

-- Configuring incomplete, errors occurred!
See also "/Users/mortenhilkerskaaning/dev/event-formation-unit/build/CMakeFiles/CMakeOutput.log".
See also "/Users/mortenhilkerskaaning/dev/event-formation-unit/build/CMakeFiles/CMakeError.log".

**Comment by mortenjc** [comment]
This is fixed now, right?

**Comment by MortenHilkerSkaaning** [comment]
yes. It got fixed in 9bf7aeb1c8c66a2f16ae877ce605bd5dc38bd6e2. Closing now.
