### ISSUE TITLE
Experiment with decreasing compile times

### ISSUE THREAD

**Issue by MortenHilkerSkaaning** [ess-dmsc/event-formation-unit#331]
Some headers contribute to slow compiles. See https://confluence.esss.lu.se/display/~mortenhilkerskaaning/Analyzing+the+compile+time+of+the+EFU
Looks like the HDF5 format, the CLI parser and the formatting library "fmt" are very heavy. I can try to wrap the headers and see how compile time is afected.

**Comment by mortenjc** [comment]
Closing this as we have no evidence that compile times are a big issue and that the ticket is old.
