### ISSUE TITLE
Data corruption problem when queue/buffer is full

### ISSUE THREAD

**Issue by SkyToGround** [ess-dmsc/event-formation-unit#4]
It appears that the way the Detector sub-classes uses CircularFifo and RingBuffer, data corruption will occur when the queue/buffer is almost full. This can possibly be solved by reducing the size of the CircularFifo. However, this solution might be error prone thus a better solution is probably to combine the functionality provided by these two classes into one single class.

**Comment by mortenjc** [comment]
I have implemented a workaround a long time ago. Since then I have not seen the 
problem. This class might be on the road to becoming obsolete, so I don't intend to
spend much more time on it.

**Comment by SkyToGround** [comment]
Feel free to close the issue if you think it is not relevant. We can open it again if it becomes a problem.
