### ISSUE TITLE
Consolidate where Logical Ring ID -> Physical Ring ID transformation takes place

### ISSUE THREAD

**Issue by JennyLouise** [ess-dmsc/event-formation-unit#501]
For Loki the transformation of Logical Ring ID to Phyiscal Ring ID happens in the parse method in DataParser.cpp, in CSPEC it happens in processReadouts method in CSPECInstrument.cpp

**Comment by mortenjc** [comment]
I'll close this one. I believe I changed the semantics so that instead of physical rings we now use fibers
and logical rings are no just rings.
