### ISSUE TITLE
Make FBSerializer fully usable

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/event-formation-unit#73]
The current way FBSerializer is, it is impossible to assign a value to any of the members, like PulseTime or sourceName because of the way the builder is used to construct everything and leave it immutable. I have already spent two hours trying to figure out how to make it change those values, but always hitting dead ends. This is SUPER HIGH PRIORITY! I can't make normal progress because of this terrible interface.

**Comment by mortenjc** [comment]
This was originally done by Jonas to speed up serializing by avoiding dynamic memory allocation. I always found it hard to understand but so far it has served its purpose. You should discuss this with Jonas, as I am not the right person to work on this. Be aware that speed is crucial for this interface so I'd suggest benchmarking when changing the code. Maybe it is better to create a new class.

But what is it you want to do which cannot be done with the current implementation?

**Comment by mortenjc** [comment]
I actually honestly don't understand why this is a blocker for your progress. I have sent an email with my phone number. Call me if you need to discuss this.

**Comment by SkyToGround** [comment]
@martukas This is not really a bug, as mentioned by Morten. As we discussed yesterday, we can sort out the implementation when we get the time and it becomes a real problem.

**Comment by martukas** [comment]
This is a serious issue, as @SkyToGround you yourself admitted in said conversation :)
1. No documentation of interface or intended functionality
2. error reporting by integer return values? I guess? Again, no explanation.
3. Timestamps in the ev42 schema are only 32 bits per event, meaning that pulse-time must be used as an additional offset to be added, if time is to be reported correctly for more than a few seconds of acquisition. Or minutes? The exact number does not matter. This needs to work. Right now it just spoofs that value as 1. Always. Even if you go in and mutate the value, write before serializing the buffer it again overwrites it with this default value. This behavior is so atrociously counterproductive it is in my mind pretty much a bug.
4. Whatever the original intended purpose of this class, it has come to be used for at least 3 if not 4 different detector pipelines. It is emphatically NOT a specialized class, but a general one that must work for all of those detectors.
5. The "whatever the reason" mentioned above happens to be premature optimization. And at the expense of correctness.

So, bad things.
Now good news, I will happily make a pull request with some if not all of these problems fixed.

**Comment by martukas** [comment]
I believe I have this in good enough shape now, as we have been able to communicate absolute timestamps for both the MG and GdGem pipelines. I am closing this.
